# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
  - 0.4
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Metrics"); Pkg.test("Metrics"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Metrics")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'